# This workflow integrates with GitHub Actions for Android and iOS builds.
#
# Key features:
# * Flutter setup and dependency resolution
# * Android: Build APK and App Bundle
# * iOS: Build IPA
# * Caching of Flutter dependencies and build artifacts
# * Triggered on pushes to the main branch and tags
# * Uses Flutter stable channel
#
# Before you start, you need to configure the following secrets in your GitHub repository:
#
#  * `ANDROID_KEYSTORE_FILE`: (Optional, for signed APK/AAB) Base64-encoded Android keystore file.
#  * `ANDROID_KEYSTORE_PASSWORD`: (Optional, for signed APK/AAB) Password for the Android keystore.
#  * `ANDROID_KEY_ALIAS`: (Optional, for signed APK/AAB) Key alias from the Android keystore.
#  * `ANDROID_KEY_PASSWORD`: (Optional, for signed APK/AAB) Password for the Android key.
#
name: Flutter CI/CD

on:
  push:
    branches:
      - main
    tags:        # Trigger on tags as well, e.g., v1.0.0
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: macos-latest # Use macOS for building both iOS and Android

    # Define build arguments as outputs.  These can be referenced by
    # dependent jobs.
    outputs:
      apk_path: ${{ steps.build_android.outputs.apk_path }}
      aab_path: ${{ steps.build_android.outputs.aab_path }}
      ipa_path: ${{ steps.build_ios.outputs.ipa_path }}
      app_name: ${{ steps.get_app_name.outputs.app_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for calculating the version

      - name: Set up Git config
        run: |
          git config --global user.name "Navjot Singh"
          git config --global user.email "navjot@gobrillianttech.com"

      - name: Get App Name
        id: get_app_name
        run: |
          APP_NAME=$(grep -o "name: " pubspec.yaml | awk -F': ' '{print $2}')
          echo "::set-output name=app_name::$APP_name"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.29.0'

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Get Flutter version
        run: |
          flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Check for updates
        run: flutter pub outdated

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage
      - name: Check formatting
        run: dart format --set-exit-if-changed .

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
      - name: Stash files that are not tracked
        run: |
          git stash --all --include-untracked

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11' # Changed to Java 11

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdkCommand: "sdkmanager --install 'platforms;android-34' 'build-tools;34.0.0' 'ndk;25.1.8937393'" # Use API 34

      - name: Build Android
        id: build_android
        if: ${{ !cancelled() }}
        run: |
          flutter build apk --split-per-abi
          flutter build appbundle
          echo "::set-output name=apk_path::build/app/outputs/flutter-apk/"
          echo "::set-output name=aab_path::build/app/outputs/bundle/"

      - name: Build iOS
        id: build_ios
        if: ${{ !cancelled() }}
        run: |
          flutter build ipa # Removed --export-options
          echo "::set-output name=ipa_path::build/ios/ipa/"

      - name: Upload APK to artifacts
        if: ${{ !cancelled() && steps.build_android.outputs.apk_path != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ${{ steps.build_android.outputs.apk_path }}
          retention-days: 5

      - name: Upload AAB to artifacts
        if: ${{ !cancelled() && steps.build_android.outputs.aab_path != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: ${{ steps.build_android.outputs.aab_path }}
          retention-days: 5

      - name: Upload IPA to artifacts
        if: ${{ !cancelled() && steps.build_ios.outputs.ipa_path != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ${{ steps.build_ios.outputs.ipa_path }}
          retention-days: 5
